apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-secrets
  namespace: kured
spec:
  encryptedData:
    values.yaml: AgBMQu68SNcAsW1C77eYh16J5Dbrb/bPuF827vVNCMXi1HSgbfcE8SG/TjhtjCwmuw/PTMafqluC7AuM3be9pfaGAcII7r7CXMMU0i2gX/xEhOzc8roz0WHqUCgwA7UVqkkAv/6J/S+9JWdKcOKimdFxfVep1Y2NKh5TTHIcbN5vp3ZAijgSNxzKheNlQqOeta06L8W1trXY5UW58sE9uMXYpSHsIZkaPsSfsj4aujQMwBhBBJzrr/1GiIC5KOcuOtS/2EaJUaVGnQMV11blUpxThWjZ1fmQxAkwBeQW5h1V5gZzoLYw20qP3xAOj6D0j8h6Uf1xITGFqUwItp0wTUpmDy8JJGmq0GWqXa9r8N3QyPZwVHDsRw+dsME4T+DL3TGTsNBkCVdfoP6cevNwOLKqkAFBKj7Ghzw+iNaXCAjeoQjVIOJjI/bFCBk6kA5yE5I6lKqf4QM5QVBV2YKpZVtff+gsAeMZHqtu5Vc8ORLZWejwLTgt1SN7psUP1xAKnzphUB3teUZdp1eVYd79nZjUNSRc/p+wmllqsuUJiHkJKWTcLm24SgVFRNqftUWcQcWpyIEiXNWBBH4BU8qJdPD/T3TsLA4PMPHSbllL0LuV2he3EBLVj4SYHfKQBnq7gIjBwxSYSHVHapt1AHuiqMC3uMOqya66RabE1lyN2rPCvF8kcrUnP5/aVfMtA/JE8Hm0IV/FP8UEuGwQfwuWwL0ijoKQi6Y5B9xo5aM0DEP941KTPC/cen7B0cuPkrcH0QktETDLK4vh3PLV2PSEnhDMdcHk0em7q/GH/VGb2LLlLWijDzg8CHwOrXUigFgNkPCkiC7WsPqewiUCr0tKjz8y5zM7Wjih6ZR0I/59NdW7E2F97z8fIQU4JFQlBcJdwYkZl6LaMtuZZtu1Al2LbQ==
  template:
    metadata:
      creationTimestamp: null
      name: slack-secrets
      namespace: kured

