apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAnHf2NIi/FgR1ZOOD7wwI4lSTK0pjSstwdK928Vx+3kHxh4v38Hw4y5aCnFw4KmEtwelUplPJXrbIYwXyagVK4QufckHcP3eqNP6KtGVlauxrO5B+2i16t0gE+zbCkwGsqSpXcyg8lLYU5Re5AiCMkBM5qWUEuTt4hnOy5UaA1+UoJKJrDsHL9dUyryFaLulNWU+47sVRYjH3DBnF3RBvWmGfxOGbB+BbivZtrGXjH9rSkAymLsvTb0KTQEaHEj1Q1elaU+JuBzckbnmz9KGKQ66jOipINPRfGtPF/YAeXMEN1xovRqRzhgxUK812RMvYCRQthT8NxRZD0kGTdFOb9ZbYFZPqmenUW9/vSLz1qQCmQr3oxwdloDssjqUZUqQ39nmPjQoHgJR9HW69bgsLl3wryfTf1+PMC8O1qqV2fHZCY7d/cKsdWRa54hT91F4N5Gjkl/giVVTHZlIQMr5Gi6jG/ESTz+OOTrB+xOt2/ujr17VdJVuVSbmMJjtjITwyQ2f0h3rHIt24XCsFa6V//c7R4YC0afJSlmdIC3cQXsAW/eCib0SwCojwidAMei3KNJNsu0R09aYZuWByb4GMIDj9pxtbHkxhI2E4mgn0h5xqmiLJROCoLyOXA/fsJAJARdw+D+V87/qihj7BtTu/QrrkmW5JsgCxQ9bn81c3cMlvNID7q3CKNXl0hboAoPvCpB9fxOxD6wMIOVsAtN0QMJuTcfGHZZXayG3+OR9VS2kk8LjN/UbKbYuUU/fZEzAYaWUiLttLkFC9IJ72vI5TCeOKMJSLWSDXrUqn9QaWJ1nnr26rbwhp9SV2NjY9oUye0JTqoY+Bk9r4x6wmjmdC+2hx23nj1om8gchoZD+SDYz57T8NX37tk6NTjqWQVW4NXKTZgh5RthjHDaubwU7IIBGjLXV+hNYsIRbwqQAn53w==
  template:
    metadata:
      creationTimestamp: null
      name: velero-crendetials
      namespace: velero
    type: Opaque

