apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgACkJERafJ8mIj6VL1Bw8xUgo+9h2BapwhM9LEpSFyKZ7uLEXTi4qgj4LL9zm4eBwTT5OO6TICINx4bKotaqjqsyvl0nH6Nm0Cpk9QFzXH5mCZG7MIBOyqQ++zOLj28m9w8tiNzQrZ5gc8OzkHowzAFRf9m720fFZh4D3tIZ+JGY0eZ/IZ9dP+j2ma6TfRSvqL7zKMocnI7MBRibj6dewckZmf3bHXAjy/+VZ7dueFQvHundvDaE/YDnYzAgyLS7nhDPA8VwGXGo/p+jrWjZnCeOXXlgddv8NxS15A08O/P7DIoj2C0X9GAcCmH++cJPxdxyCDXd3OfMVvVXZy4aWQE0w4HUIqCy/fT4+tkmPD4XOsn1p775lUuKwEM5p5Bcx+5ApUKeIdWGa9I8qrC7XHc7A4uOeCNMKMoiOJ+/VmiZAO8971amgQPOolKaOI4Ef+y7KarwO+K2ysfz6sQArs8vEHbjk9Y50KgdheG2RG2mSSXar6TZEJ/Yc2FjWPizEBjQWWpUMefQI7yTDVYTFxl2iyBMRt8lDf4IL1Fe5GA9NWX5P0Fa2LiBR1W+q+VyjNdud7W+KVXEmLEeVvta6plzV1Dcq7RkWTc90ItLthfSISXbOS0Oh4IVSi+L5Vzt9AgJ9KUFOsLy1Y4CaRNaztE8F9ZD3Eri4vXBL4ZRA5EhzPYQPnfYh/CuQmnQD5peG3aks/+UVINVgYcEQTgBZuhBIexxoB4mokVNEu+5rd+by2AuUAEWTsEivjOOR/DOjqYUW975JPQ7O60
  template:
    metadata:
      creationTimestamp: null
      name: velero-crendetials
      namespace: velero
    type: Opaque

